# Generated by Django 5.2.3 on 2025-06-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_termsandconditions_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
